// functions/api/textbooks.js
//
// Static-JSON-backed API with Cache API + Kerala upstream fallback.
//
// 1. Static JSON fast-path (from /data/textbooks/): edge-delivered, no binding.
// 2. Cache API fallback (per-POP, 1-hour TTL).
// 3. Kerala upstream (last resort, 2-8s).
//
// The static JSON files are generated by scripts/sync.js and committed
// alongside the site. No KV binding needed.

const KERALA = 'https://samagra.kite.kerala.gov.in/v2/api/public/getSubjectTextbooks';
const CACHE_TTL = 3600; // 1 hour

const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'access-control-allow-origin': '*',
  'cache-control': `public, max-age=${CACHE_TTL}, stale-while-revalidate=${CACHE_TTL}`,
};

function emptyResponse(mediumId, classId) {
  return {
    textbooks: [],
    subjects: [],
    total: 0,
    mediumId,
    classId,
  };
}

function buildCacheKey(request) {
  // Cache by full query (medium/class/subject/search). Vary partitioning
  // is intentionally not used; the query string is the cache key.
  return new Request(request.url, { method: 'GET' });
}

function mapSubjects(rawSubjects) {
  return rawSubjects.map((s) => ({
    id: Number(s.id),
    subjectName: s.subjectName ?? null,
    subjectGroupId: s.subjectGroupId != null ? Number(s.subjectGroupId) : null,
  }));
}

/**
 * Apply in-memory subject and search filtering to cached data.
 */
function filterInMemory(data, mediumId, classId, subjectId, search) {
  let textbooks = data.textbooks || [];
  const q = search ? search.toLowerCase() : '';

  // Subject filter
  if (subjectId != null && !Number.isNaN(subjectId)) {
    textbooks = textbooks.filter((t) => t.subjectId === subjectId);
  }

  // Search filter
  if (q) {
    textbooks = textbooks.filter((t) => {
      const cn = t.chapterName;
      const sn = t.subjectName;
      return (cn && cn.toLowerCase().includes(q)) || (sn && sn.toLowerCase().includes(q));
    });
  }

  return {
    textbooks,
    subjects: data.subjects || [],
    total: textbooks.length,
    mediumId,
    classId,
  };
}

export async function onRequest(context) {
  const { request } = context;
  const url = new URL(request.url);

  const mediumId = Number(url.searchParams.get('medium')) || 2;
  const classId = Number(url.searchParams.get('class')) || 12;
  const subjectParam = url.searchParams.get('subject');
  const subjectId = subjectParam ? Number(subjectParam) : null;
  const search = (url.searchParams.get('search') || '').trim();

  // ── 1. Static JSON fast-path (edge-delivered, from scripts/sync.js) ──────────
  // Fetch from our own deployed static JSON files. No KV binding needed.
  try {
    const jsonUrl = `${url.origin}/data/textbooks/${mediumId}/${classId}.json`;
    const jsonRes = await fetch(jsonUrl);
    if (jsonRes.ok) {
      const parsed = await jsonRes.json();
      const result = filterInMemory(parsed, mediumId, classId, subjectId, search);
      return new Response(JSON.stringify(result), { headers: JSON_HEADERS });
    }
  } catch (e) {
    // JSON file missing or error — fall through to Cache API + Kerala
  }

  // ── 2. Cache API fallback (per-POP, 1-hour TTL) ──────────────────────
  try {
    const cache = caches.default;
    const cacheKey = buildCacheKey(request);
    const cached = await cache.match(cacheKey);
    if (cached) {
      // Re-emit with refreshed CORS header (Cloudflare strips sometimes).
      return new Response(cached.body, { headers: JSON_HEADERS });
    }
  } catch (e) {
    // Cache failure is non-fatal; fall through to live fetch.
  }

  // ── 3. Live fetch from Kerala (last resort) ──────────────────────────
  let body;
  try {
    const keralaRes = await fetch(`${KERALA}/${mediumId}/${classId}`, {
      headers: { 'User-Agent': 'Mozilla/5.0 (samagra-mirror)' },
      signal: AbortSignal.timeout(15_000),
    });
    if (!keralaRes.ok) {
      return new Response(
        JSON.stringify({ error: `Kerala upstream returned ${keralaRes.status}`, ...emptyResponse(mediumId, classId) }),
        { status: 502, headers: { ...JSON_HEADERS, 'cache-control': 'no-store' } }
      );
    }
    body = await keralaRes.json();
  } catch (err) {
    return new Response(
      JSON.stringify({ error: `Kerala upstream unreachable: ${err.message}`, ...emptyResponse(mediumId, classId) }),
      { status: 502, headers: { ...JSON_HEADERS, 'cache-control': 'no-store' } }
    );
  }

  if (!body || body.status !== 'success' || !body.data) {
    return new Response(
      JSON.stringify({ error: `Kerala upstream rejected: status=${body?.status}`, ...emptyResponse(mediumId, classId) }),
      { status: 502, headers: { ...JSON_HEADERS, 'cache-control': 'no-store' } }
    );
  }

  const rawSubjects = Array.isArray(body.data.subjectData) ? body.data.subjectData : [];
  const rawTextbooks = Array.isArray(body.data.textbookData) ? body.data.textbookData : [];

  // Kerala returns the full subject catalog (~40 subjects) for every
  // (medium, class) request, regardless of medium. Most of these are orphan
  // in the corresponding textbookData (German, Russian, Latin, Syriac,
  // Urdu, French, ...). Culling them down to subjects that have ≥1 textbook
  // here gives the wheel a sane, medium-coherent list.
  const visibleSubjectIds = new Set();
  for (const t of rawTextbooks) {
    if (t && t.subjectId != null) visibleSubjectIds.add(Number(t.subjectId));
  }
  const filteredSubjects = rawSubjects.filter(
    (s) => s && s.id != null && visibleSubjectIds.has(Number(s.id))
  );

  // Build a join map so we can stamp subjectName per textbook.
  const subjectsById = new Map();
  for (const s of filteredSubjects) {
    if (s && s.id != null) subjectsById.set(Number(s.id), s);
  }

  // Map textbooks + apply filters in a single pass
  const hasSubjFilter = subjectId != null && !Number.isNaN(subjectId);
  const q = search ? search.toLowerCase() : '';
  const textbooks = [];
  for (const t of rawTextbooks) {
    if (!t) continue;

    // Subject filter
    if (hasSubjFilter && Number(t.subjectId) !== subjectId) continue;

    const subj = subjectsById.get(Number(t.subjectId));
    const sn = subj ? subj.subjectName : null;

    // Search filter
    if (search) {
      const cn = t.chapterName;
      const cnMatch = cn && cn.toLowerCase().includes(q);
      const snMatch = sn && sn.toLowerCase().includes(q);
      if (!cnMatch && !snMatch) continue;
    }

    const pdfRel = (t.chapterPdfUrl || '').replace(/^\/+/, '');
    const thumbRel = (t.chapterThumbUrl || '').replace(/^\/+/, '');
    textbooks.push({
      id: Number(t.id),
      chapterName: t.chapterName ?? null,
      mediumId,
      classId,
      subjectId: t.subjectId != null ? Number(t.subjectId) : null,
      pdfUrl: pdfRel ? `/files/${pdfRel}` : null,
      thumbUrl: thumbRel ? `/files/${thumbRel}` : null,
      downloadState: 'complete',
      subjectName: sn,
    });
  }

  const responseBody = {
    textbooks,
    subjects: mapSubjects(filteredSubjects),
    total: textbooks.length,
    mediumId,
    classId,
  };

  const response = new Response(JSON.stringify(responseBody), { headers: JSON_HEADERS });

  // 4. Best-effort cache the response (ignore cache failures).
  try {
    const cache = caches.default;
    const cacheKey = buildCacheKey(request);
    // Cache needs a Response with explicit Cache-Control; we already set one.
    await cache.put(cacheKey, response.clone());
  } catch (e) {
    // ignore
  }

  return response;
}
