#!/usr/bin/env node
/**
 * scripts/ingest-d1.mjs
 *
 * Refreshes the Cloudflare D1 mirror (samagra-textbooks) from the live Kerala
 * SCERT API. Hits all 48 endpoints (4 mediums × 12 classes) in parallel,
 * aggregates subjects + textbooks, and emits a single SQL file at
 * /tmp/ingest.sql that can be applied with:
 *
 *   npx wrangler d1 execute samagra-textbooks --remote --file=/tmp/ingest.sql
 *
 * Idempotency strategy:
 *   - mediums:    INSERT OR IGNORE (static 1-4)
 *   - subjects:   INSERT ... ON CONFLICT(id) DO UPDATE  (Kerala ids are stable)
 *   - m_c_subj:   INSERT OR REPLACE                    (composite PK)
 *   - textbooks:  DELETE ALL + INSERT                  (fresh catalog from Kerala)
 *
 * `pdf_url` is stored as `/files/<relative-path>` so the existing
 * /files/[[path]].js worker proxies it correctly to Kerala's CDN.
 */

import { writeFile } from 'node:fs/promises';

const API = 'https://samagra.kite.kerala.gov.in/v2/api/public/getSubjectTextbooks';
const MEDIUMS = [
  { id: 1, name: 'Malayalam' },
  { id: 2, name: 'English' },
  { id: 3, name: 'Tamil' },
  { id: 4, name: 'Kannada' },
];
const CLASSES = Array.from({ length: 12 }, (_, i) => i + 1);
const CONCURRENCY = 8;

// ---------- helpers ----------

function sqlStr(s) {
  if (s === null || s === undefined) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function sqlInt(n) {
  if (n === null || n === undefined || Number.isNaN(Number(n))) return 'NULL';
  return String(Number(n));
}

function toRelativePath(raw) {
  if (!raw) return null;
  if (raw.startsWith('http')) {
    try {
      const u = new URL(raw);
      return u.pathname.replace(/^\//, '');
    } catch {
      return raw.replace(/^\//, '');
    }
  }
  return raw.replace(/^\//, '');
}

function buildPdfUrl(raw) {
  const rel = toRelativePath(raw);
  if (!rel) return null;
  return rel.startsWith('/files/') ? rel : `/files/${rel}`;
}

function buildApiUrl(raw) {
  if (!raw) return null;
  if (raw.startsWith('http')) return raw;
  if (raw.startsWith('/')) return `https://samagra.kite.kerala.gov.in${raw}`;
  return `https://samagra.kite.kerala.gov.in/${raw}`;
}

// ---------- network ----------

async function fetchEndpoint(mediumId, classId) {
  const url = `${API}/${mediumId}/${classId}`;
  const res = await fetch(url, {
    headers: { 'User-Agent': 'samagra-mirror/1.0 (+https://samagra-textbooks.pages.dev)' },
    signal: AbortSignal.timeout(20_000),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText} for ${url}`);
  const body = await res.json();
  if (!body || body.status !== 'success') throw new Error(`status=${body?.status} for ${url}`);
  const data = body.data || {};
  return {
    mediumId,
    classId,
    subjects: Array.isArray(data.subjectData) ? data.subjectData : [],
    textbooks: Array.isArray(data.textbookData) ? data.textbookData : [],
  };
}

async function fetchAll() {
  const tasks = MEDIUMS.flatMap((m) => CLASSES.map((c) => [m.id, c]));
  console.error(`[ingest] fetching ${tasks.length} endpoints (concurrency=${CONCURRENCY})...`);

  const results = [];
  const failures = [];
  let cursor = 0;

  async function worker() {
    while (cursor < tasks.length) {
      const i = cursor++;
      const [m, c] = tasks[i];
      try {
        const r = await fetchEndpoint(m, c);
        results.push(r);
        console.error(`[ingest]   ok   ${m}/${c}  subjects=${r.subjects.length}  textbooks=${r.textbooks.length}`);
      } catch (e) {
        failures.push({ endpoint: `${m}/${c}`, error: e.message });
        console.error(`[ingest]   FAIL ${m}/${c}  ${e.message}`);
      }
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));
  return { results, failures };
}

// ---------- SQL builder ----------

function buildSql(results) {
  const sql = [];
  sql.push('-- ============================================================');
  sql.push('-- Auto-generated by scripts/ingest-d1.mjs');
  sql.push(`-- ${new Date().toISOString()}`);
  sql.push(`-- D1 database: samagra-textbooks  binding: TEXTBOOKS_DB`);
  sql.push('-- Idempotent: safe to re-run.');
  sql.push('-- ============================================================');
  sql.push('');

  // --- mediums ---
  sql.push('-- mediums (static, 1-4)');
  sql.push('INSERT OR IGNORE INTO mediums (id, name) VALUES');
  sql.push(MEDIUMS.map((m) => `  (${sqlInt(m.id)}, ${sqlStr(m.name)})`).join(',\n') + ';');
  sql.push('');

  // --- subjects ---
  const subjectsById = new Map();
  for (const r of results) {
    for (const s of r.subjects) {
      if (s && s.id !== undefined && s.id !== null) {
        subjectsById.set(Number(s.id), {
          id: Number(s.id),
          name: s.subjectName ?? null,
          groupId: s.subjectGroupId ?? null,
        });
      }
    }
  }
  const subjectRows = [...subjectsById.values()].sort((a, b) => a.id - b.id);

  sql.push(`-- subjects (${subjectRows.length} unique)`);
  sql.push('INSERT INTO subjects (id, name, group_id) VALUES');
  sql.push(subjectRows.map((s) => `  (${sqlInt(s.id)}, ${sqlStr(s.name)}, ${sqlInt(s.groupId)})`).join(',\n'));
  sql.push('ON CONFLICT(id) DO UPDATE SET name = excluded.name, group_id = excluded.group_id;');
  sql.push('');

  // --- medium_class_subjects ---
  const mcsDedup = new Set();
  const mcsRows = [];
  for (const r of results) {
    for (const s of r.subjects) {
      if (s?.id == null) continue;
      const key = `${r.mediumId}|${r.classId}|${s.id}`;
      if (mcsDedup.has(key)) continue;
      mcsDedup.add(key);
      mcsRows.push(`(${sqlInt(r.mediumId)}, ${sqlInt(r.classId)}, ${sqlInt(s.id)})`);
    }
  }

  sql.push(`-- medium_class_subjects (${mcsRows.length} mappings)`);
  sql.push('INSERT OR REPLACE INTO medium_class_subjects (medium_id, class_id, subject_id) VALUES');
  sql.push(mcsRows.map((r) => '  ' + r).join(',\n') + ';');
  sql.push('');

  // --- textbooks ---
  const tbDedup = new Set();
  const tbRows = [];
  let droppedTb = 0;
  for (const r of results) {
    if (!r.textbooks || r.textbooks.length === 0) continue;
    for (const t of r.textbooks) {
      if (!t || t.id == null) {
        droppedTb++;
        continue;
      }
      const dedupKey = `${t.id}|${r.mediumId}|${r.classId}`;
      if (tbDedup.has(dedupKey)) continue;
      tbDedup.add(dedupKey);

      const sourceId = Number(t.id);
      const chapterName = t.chapterName ?? null;
      const subjectId = t.subjectId != null ? Number(t.subjectId) : null;
      const apiPdfUrl = buildApiUrl(t.chapterPdfUrl);
      const apiThumbUrl = buildApiUrl(t.chapterThumbUrl);
      const pdfUrl = buildPdfUrl(t.chapterPdfUrl);
      const thumbUrl = buildPdfUrl(t.chapterThumbUrl);

      tbRows.push(
        `  (${sqlInt(sourceId)}, ${sqlStr(chapterName)}, ${sqlInt(r.mediumId)}, ${sqlInt(r.classId)}, ${sqlInt(subjectId)}, ${sqlStr(apiPdfUrl)}, ${sqlStr(apiThumbUrl)}, ${sqlStr(pdfUrl)}, ${sqlStr(thumbUrl)}, NULL, 'complete', datetime('now'))`
      );
    }
  }

  sql.push('-- textbooks: wipe and re-insert as chunks (D1 per-statement size cap)');
  sql.push('DELETE FROM textbooks;');
  sql.push('');

  // D1 rejects any single statement over ~100KB with SQLITE_TOOBIG. Each row
  // here is ~250 bytes, so cap each INSERT at 150 rows (~37KB) for headroom.
  const TEXTBOOK_CHUNK = 150;
  const totalBatches = Math.ceil(tbRows.length / TEXTBOOK_CHUNK) || 1;
  for (let i = 0; i < tbRows.length; i += TEXTBOOK_CHUNK) {
    const slice = tbRows.slice(i, i + TEXTBOOK_CHUNK);
    const batchNum = Math.floor(i / TEXTBOOK_CHUNK) + 1;
    sql.push(
      `-- textbooks batch ${batchNum}/${totalBatches} (rows ${i + 1}..${Math.min(i + TEXTBOOK_CHUNK, tbRows.length)})`
    );
    sql.push(
      'INSERT INTO textbooks (source_id, chapter_name, medium_id, class_id, subject_id, api_pdf_url, api_thumb_url, pdf_url, thumb_url, file_size, download_state, updated_at) VALUES'
    );
    sql.push(slice.join(',\n') + ';');
    sql.push('');
  }

  return sql.join('\n');
}

// ---------- main ----------

async function main() {
  const startedAt = Date.now();
  const { results, failures } = await fetchAll();

  const subjectCount = new Set(results.flatMap((r) => r.subjects.map((s) => s.id))).size;
  const textbookCount = results.reduce((n, r) => n + r.textbooks.length, 0);

  console.error(
    `[ingest] done in ${((Date.now() - startedAt) / 1000).toFixed(1)}s — ${results.length}/${
      MEDIUMS.length * CLASSES.length
    } endpoints, ${subjectCount} subjects, ${textbookCount} textbooks (failures=${failures.length})`
  );

  if (failures.length === MEDIUMS.length * CLASSES.length) {
    throw new Error('All endpoints failed; refusing to emit SQL.');
  }

  const sql = buildSql(results);
  await writeFile('/tmp/ingest.sql', sql, 'utf8');
  console.error(`[ingest] wrote /tmp/ingest.sql (${(sql.length / 1024).toFixed(1)} KB, ${sql.split('\n').length} lines)`);
  console.error('[ingest] next:  bash scripts/apply-ingest.sh   (or run `npx wrangler d1 execute samagra-textbooks --remote --file=/tmp/ingest.sql --yes`)');
}

main().catch((e) => {
  console.error('[ingest] FATAL', e);
  process.exit(1);
});
